# Generated by Django 3.2.4 on 2021-06-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Null', max_length=10),
            preserve_default=False,
        ),
    ]
