# Generated by Django 3.2.4 on 2021-06-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='app_no',
        ),
    ]
